-- ============================================================
-- LogiTrack
-- Archivo: src/main/resources/schema.sql
-- Base de datos: PostgreSQL
-- ============================================================

-- Este script elimina primero las tablas para permitir una
-- creación limpia durante el desarrollo académico.
-- No debe ejecutarse de forma automática en producción porque
-- elimina todos los datos existentes.

DROP TABLE IF EXISTS auditorias CASCADE;
DROP TABLE IF EXISTS detalles_movimiento CASCADE;
DROP TABLE IF EXISTS movimientos CASCADE;
DROP TABLE IF EXISTS inventarios CASCADE;
DROP TABLE IF EXISTS bodegas CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;


-- ============================================================
-- Tabla: usuarios
-- Almacena los usuarios que pueden autenticarse en LogiTrack.
-- ============================================================

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_usuarios
        PRIMARY KEY (id),

    CONSTRAINT uk_usuarios_username
        UNIQUE (username),

    CONSTRAINT chk_usuarios_nombre
        CHECK (CHAR_LENGTH(TRIM(nombre)) >= 2),

    CONSTRAINT chk_usuarios_username
        CHECK (CHAR_LENGTH(TRIM(username)) >= 3),

    CONSTRAINT chk_usuarios_password
        CHECK (CHAR_LENGTH(password) >= 6),

    CONSTRAINT chk_usuarios_rol
        CHECK (rol IN ('ADMIN', 'EMPLEADO'))
);


-- ============================================================
-- Tabla: productos
-- Almacena la información general de cada producto.
-- El stock no se guarda en esta tabla.
-- ============================================================

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    precio NUMERIC(15, 2) NOT NULL,

    CONSTRAINT pk_productos
        PRIMARY KEY (id),

    CONSTRAINT chk_productos_nombre
        CHECK (CHAR_LENGTH(TRIM(nombre)) >= 2),

    CONSTRAINT chk_productos_categoria
        CHECK (CHAR_LENGTH(TRIM(categoria)) >= 2),

    CONSTRAINT chk_productos_precio
        CHECK (precio > 0)
);


-- ============================================================
-- Tabla: bodegas
-- Almacena las bodegas administradas por LogiTrack.
-- Cada bodega puede tener un usuario encargado.
-- ============================================================

CREATE TABLE bodegas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    ubicacion VARCHAR(150) NOT NULL,
    capacidad INTEGER NOT NULL,
    encargado_id BIGINT NOT NULL,

    CONSTRAINT pk_bodegas
        PRIMARY KEY (id),

    CONSTRAINT chk_bodegas_nombre
        CHECK (CHAR_LENGTH(TRIM(nombre)) >= 2),

    CONSTRAINT chk_bodegas_ubicacion
        CHECK (CHAR_LENGTH(TRIM(ubicacion)) >= 2),

    CONSTRAINT chk_bodegas_capacidad
        CHECK (capacidad > 0),

    CONSTRAINT fk_bodegas_encargado
        FOREIGN KEY (encargado_id)
        REFERENCES usuarios (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================
-- Tabla: inventarios
-- Almacena el stock de cada producto en cada bodega.
-- Una combinación bodega-producto solamente puede existir una vez.
-- ============================================================

CREATE TABLE inventarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    bodega_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT pk_inventarios
        PRIMARY KEY (id),

    CONSTRAINT uk_inventarios_bodega_producto
        UNIQUE (bodega_id, producto_id),

    CONSTRAINT chk_inventarios_stock
        CHECK (stock >= 0),

    CONSTRAINT fk_inventarios_bodega
        FOREIGN KEY (bodega_id)
        REFERENCES bodegas (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_inventarios_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================
-- Tabla: movimientos
-- Registra entradas, salidas y transferencias de inventario.
--
-- ENTRADA:
--   bodega_origen_id debe ser NULL.
--   bodega_destino_id debe contener una bodega.
--
-- SALIDA:
--   bodega_origen_id debe contener una bodega.
--   bodega_destino_id debe ser NULL.
--
-- TRANSFERENCIA:
--   ambas bodegas son obligatorias y deben ser diferentes.
-- ============================================================

CREATE TABLE movimientos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo VARCHAR(20) NOT NULL,
    usuario_responsable_id BIGINT NOT NULL,
    bodega_origen_id BIGINT,
    bodega_destino_id BIGINT,

    CONSTRAINT pk_movimientos
        PRIMARY KEY (id),

    CONSTRAINT chk_movimientos_tipo
        CHECK (
            tipo IN (
                'ENTRADA',
                'SALIDA',
                'TRANSFERENCIA'
            )
        ),

    CONSTRAINT chk_movimientos_bodegas
        CHECK (
            (
                tipo = 'ENTRADA'
                AND bodega_origen_id IS NULL
                AND bodega_destino_id IS NOT NULL
            )
            OR
            (
                tipo = 'SALIDA'
                AND bodega_origen_id IS NOT NULL
                AND bodega_destino_id IS NULL
            )
            OR
            (
                tipo = 'TRANSFERENCIA'
                AND bodega_origen_id IS NOT NULL
                AND bodega_destino_id IS NOT NULL
                AND bodega_origen_id <> bodega_destino_id
            )
        ),

    CONSTRAINT fk_movimientos_usuario_responsable
        FOREIGN KEY (usuario_responsable_id)
        REFERENCES usuarios (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimientos_bodega_origen
        FOREIGN KEY (bodega_origen_id)
        REFERENCES bodegas (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimientos_bodega_destino
        FOREIGN KEY (bodega_destino_id)
        REFERENCES bodegas (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================
-- Tabla: detalles_movimiento
-- Relaciona cada movimiento con sus productos y cantidades.
-- ============================================================

CREATE TABLE detalles_movimiento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movimiento_id BIGINT NOT NULL,
    producto_id BIGINT NOT NULL,
    cantidad INTEGER NOT NULL,

    CONSTRAINT pk_detalles_movimiento
        PRIMARY KEY (id),

    CONSTRAINT uk_detalles_movimiento_movimiento_producto
        UNIQUE (movimiento_id, producto_id),

    CONSTRAINT chk_detalles_movimiento_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT fk_detalles_movimiento_movimiento
        FOREIGN KEY (movimiento_id)
        REFERENCES movimientos (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_detalles_movimiento_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- ============================================================
-- Tabla: auditorias
-- Almacena la trazabilidad de inserciones, actualizaciones y
-- eliminaciones realizadas sobre las entidades del sistema.
-- ============================================================

CREATE TABLE auditorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_operacion VARCHAR(20) NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario VARCHAR(100) NOT NULL,
    entidad_afectada VARCHAR(100) NOT NULL,
    entidad_id BIGINT,
    valores_anteriores TEXT,
    valores_nuevos TEXT,

    CONSTRAINT pk_auditorias
        PRIMARY KEY (id),

    CONSTRAINT chk_auditorias_tipo_operacion
        CHECK (
            tipo_operacion IN (
                'INSERT',
                'UPDATE',
                'DELETE'
            )
        ),

    CONSTRAINT chk_auditorias_usuario
        CHECK (CHAR_LENGTH(TRIM(usuario)) > 0),

    CONSTRAINT chk_auditorias_entidad
        CHECK (
            CHAR_LENGTH(TRIM(entidad_afectada)) > 0
        )
);


-- ============================================================
-- Índices
-- Mejoran las búsquedas utilizadas por los repositorios y
-- reportes del proyecto.
-- ============================================================

CREATE INDEX idx_bodegas_encargado
    ON bodegas (encargado_id);

CREATE INDEX idx_productos_nombre
    ON productos (nombre);

CREATE INDEX idx_productos_categoria
    ON productos (categoria);

CREATE INDEX idx_inventarios_bodega
    ON inventarios (bodega_id);

CREATE INDEX idx_inventarios_producto
    ON inventarios (producto_id);

CREATE INDEX idx_inventarios_stock
    ON inventarios (stock);

CREATE INDEX idx_movimientos_fecha
    ON movimientos (fecha);

CREATE INDEX idx_movimientos_tipo
    ON movimientos (tipo);

CREATE INDEX idx_movimientos_usuario
    ON movimientos (usuario_responsable_id);

CREATE INDEX idx_movimientos_bodega_origen
    ON movimientos (bodega_origen_id);

CREATE INDEX idx_movimientos_bodega_destino
    ON movimientos (bodega_destino_id);

CREATE INDEX idx_detalles_movimiento_movimiento
    ON detalles_movimiento (movimiento_id);

CREATE INDEX idx_detalles_movimiento_producto
    ON detalles_movimiento (producto_id);

CREATE INDEX idx_auditorias_fecha_hora
    ON auditorias (fecha_hora);

CREATE INDEX idx_auditorias_usuario
    ON auditorias (usuario);

CREATE INDEX idx_auditorias_tipo_operacion
    ON auditorias (tipo_operacion);

CREATE INDEX idx_auditorias_entidad
    ON auditorias (entidad_afectada, entidad_id);